[be] Написать бекэнд для страницы рег/входа
go-park-mail-ru/2024_2_kotyari pull request #1
Opened 2024-09-20 21:12 UTC by JOJOSoderqvist

feat: Добавлена регистрация
P.S. Санитайзер на уровне - что в голову пришло, позже будет исправлен в соответствии с общими требованиями к санитайзингу в т.ч. на фронте

2024-09-21 17:50 UTC, goriiin commented
нужны тесты

2024-09-21 18:00 UTC, goriiin requested changes

2024-09-22 12:05 UTC, JOJOSoderqvist commented on custom_errors/custom_errors.go
> +}
Сделал

2024-09-22 12:06 UTC, JOJOSoderqvist commented on db/db.go
> +	}
Сделал

2024-09-22 12:06 UTC, JOJOSoderqvist commented on api/signup.go
> +		})
Сделал

2024-09-22 13:41 UTC, goriiin requested changes

2024-09-22 13:41 UTC, goriiin commented on api/signup.go
> +	if err != nil {
перенос строки после var,
убрать перенос после NewDecoder

2024-09-22 13:41 UTC, goriiin commented on db/db.go
> +var users = make(map[string]User)
лучше сделать отдельную структуру с sync.Mutex, так как при работе с мапой в горутинах -- неизбежная паника

2024-09-22 13:41 UTC, goriiin commented on api/signup.go
> +	err = db.CreateUser(signupRequest.Email, signupRequest.User)
нужно хэширование пароля, используй Argon2

2024-09-23 20:56 UTC, goriiin approved these changes

2024-09-23 22:51 UTC, HallowAz commented on api/signup.go
> +	if len(signupRequest.Username) < 3 || len(signupRequest.Username) > 20 {
minUsernameLen, maxUsernameLen (понимаете про что я)

2024-09-23 22:52 UTC, HallowAz commented on api/signup.go
> +	if len(signupRequest.Password) < 5 {
same

2024-09-23 22:53 UTC, HallowAz commented on api/types.go
> +	db.User
явно назвать поле надо

2024-09-23 22:53 UTC, HallowAz commented on cmd/main.go
> +	_ = http.ListenAndServe("127.0.0.1:8080", nil)
если роняете сервак, лучше напишите об этом сообщение в консоль

2024-09-23 22:54 UTC, HallowAz approved these changes

2024-09-25 17:08 UTC, merged