[OZON-76] User по чистой архитектуре
go-park-mail-ru/2024_2_kotyari pull request #17
Opened 2024-10-13 15:02 UTC by JOJOSoderqvist

2024-10-13 22:07 UTC, goriiin requested changes

2024-10-13 22:07 UTC, goriiin commented on internal/delivery/user/handler.go
> +type Delivery struct {
предлагаю добавить логгирование

2024-10-13 22:07 UTC, goriiin commented on internal/handlers/auth.go
>  type AuthApp struct {
мне кажется handlers и delivery все таки одно и то же

2024-10-14 20:00 UTC, HallowAz commented on internal/delivery/user/handler.go
> +}
бизнес логику убрать на слой юзкейса

2024-10-14 20:02 UTC, HallowAz commented on internal/model/user.go
>  	Password       string `json:"password"`
это не модель, это дто

2024-10-17 21:36 UTC, HallowAz commented on internal/delivery/auth/auth_manager.go
> +		Delivery: *user.NewUserDelivery(userU.NewUserUsecase(userR.NewUserMapRepository())),
неправильно, не через интерфейсы делаешь. Такой код не тестируется и незаменяем

2024-10-17 21:37 UTC, HallowAz commented on internal/delivery/auth/auth_manager.go
> +}
нужно мокать, а это не моки

2024-10-17 21:37 UTC, HallowAz commented on internal/delivery/auth/auth_manager.go
> +	Delivery user.Delivery
почему здесь структура? Нужен интерфейс

2024-10-17 21:38 UTC, HallowAz commented on internal/delivery/auth/auth_manager.go
> +	setSessionOptions(session, 10*hour)
что за 10

2024-10-17 21:39 UTC, HallowAz commented on internal/delivery/auth/auth_manager.go
> +	session.Values = make(map[interface{}]interface{})
зачем это?

2024-10-17 21:39 UTC, HallowAz commented on internal/delivery/auth/auth_manager.go
> +func (am *Manager) Soon(w http.ResponseWriter, r *http.Request) {
по названию не понимаю что делает метод

2024-10-17 21:42 UTC, HallowAz commented on internal/delivery/user/handler.go
> +type UsecaseInterface interface {
называть надо самодокументирующим названием. Мне ничего не дает название usecaseinterface.

Правильным было бы название userManger или userService или userUsecase (хотя последний вариант мне меньше всего нравится.

2024-10-17 21:43 UTC, HallowAz commented on internal/delivery/user/handler.go
> +	CreateUser(userSignupRequest *model.UserSignupRequestDTO) (*model.User, error)
зачем по указателю передавать эти параметры? И возвращать? В гошке принято по значению передавать и возвращать без явной необходимости. Плюс методы становятся нетестируемыми, узнаешь, когда начнешь тесты писать на них

2024-10-17 21:44 UTC, HallowAz commented on internal/delivery/user/handler.go
> +}
вот здесь правильно, так у тебя сохраняется независимость от реализации

2024-10-17 21:46 UTC, HallowAz commented on internal/delivery/user/handler.go
> +func (d *Delivery) LoginByEmail(r *http.Request) (*model.User, error) {
слой деливери должен занимать парсингом и маршаллингом запросов и ответов, у тебя почему-то из него модель выходит, это неправильно, деливери это уже конечный слой

2024-10-17 21:46 UTC, HallowAz commented on internal/middlewares/auth.go
> +	"github.com/go-park-mail-ru/2024_2_kotyari/internal/utils"
поправь

2024-10-17 21:48 UTC, HallowAz commented on internal/middlewares/auth.go
> +			ctx := context.WithValue(r.Context(), "username", user.Username)
зачем это

2024-10-17 21:50 UTC, HallowAz commented on internal/usecase/user/usecase.go
> +type RepoInterface interface {
опять же, название неправильное. Лучше назвать userStorer. И делать его надо приватным.

 Когда у тебя будет несколько репозиториев, ты не будешь понимать какой за что отвечаео

2024-10-17 21:51 UTC, HallowAz commented on internal/usecase/user/usecase.go
> +	return u.repo.GetUserByEmail(userLoginRequest.Email)
где проверка пролей и прочее?

2024-10-17 21:51 UTC, HallowAz commented on internal/usecase/user/usecase.go
> +	return u.repo.GetUserByEmail(userLoginRequest.Email)
Если у тебя метод просто вызывает следующий слой, то зачем тебе такой метод

2024-10-17 21:51 UTC, HallowAz commented on internal/usecase/user/usecase.go
> +	return u.repo.GetUserByEmail(email)
зачем тебе такой метод

2024-10-17 21:52 UTC, HallowAz commented on internal/utils/json.go
> +	}
почему ошибку не обрабатываешь

2024-10-18 14:54 UTC, JOJOSoderqvist commented on internal/delivery/auth/auth_manager.go
> +	session.Values = make(map[interface{}]interface{})
Убрал

2024-10-18 15:28 UTC, JOJOSoderqvist commented on internal/delivery/user/handler.go
> +	CreateUser(userSignupRequest *model.UserSignupRequestDTO) (*model.User, error)
С плюсов привык все по указателю передавать

2024-10-18 18:51 UTC, JOJOSoderqvist commented on internal/delivery/auth/auth_manager.go
> +	setSessionOptions(session, 10*hour)
Исправил

2024-10-18 19:02 UTC, JOJOSoderqvist commented on internal/delivery/auth/auth_manager.go
> +		Delivery: *user.NewUserDelivery(userU.NewUserUsecase(userR.NewUserMapRepository())),
Поправил

2024-10-18 19:07 UTC, JOJOSoderqvist commented on internal/model/user_dto.go
> +	RepeatPassword string `json:"repeat_password"`
Тут вроде смысл был в том что в будущем могут быть разные клиенты, где может не быть подобной валидации и типа лучше перестраховаться

2024-10-18 19:12 UTC, JOJOSoderqvist commented on internal/usecase/user/usecase.go
> +type RepoInterface interface {
Исправил, но приватным его сделать не получится (Как и почти все остальные интерфейсы) потому что реализация находится на уровень ниже

2024-10-18 19:25 UTC, JOJOSoderqvist commented on internal/utils/json.go
> +	}
Я просто не совсем понимаю как ее обрабатывать на уровень выше. Мне кажется можно добавить что-то в духе
```go

2024-10-18 19:27 UTC, JOJOSoderqvist commented on internal/usecase/user/usecase.go
> +	return u.repo.GetUserByEmail(userLoginRequest.Email)
Исправил

2024-10-18 19:54 UTC, JOJOSoderqvist commented on internal/usecase/user/usecase.go
> +	return u.repo.GetUserByEmail(userLoginRequest.Email)
Это костыль для middleware. Я пока не совсем понимаю как оттуда можно добраться до пользователя без вот этих вспомогательных методов

2024-10-18 20:15 UTC, JOJOSoderqvist commented on internal/usecase/user/usecase.go
> +	return u.repo.GetUserByEmail(email)
А как иначе попасть на слой репозитория? Я же не могу в handler-e написать
```go
delivery.usecase.repository.GetUserByEmail()
```
потому что usecase это интерфейс

2024-10-18 20:33 UTC, JOJOSoderqvist commented on internal/delivery/auth/auth_manager.go
> +func (am *Manager) Soon(w http.ResponseWriter, r *http.Request) {
Исправил

2024-10-18 22:02 UTC, JOJOSoderqvist commented on internal/utils/json.go
> +	}
Ну или если в middleware проверять только наличие сессии, то можно вообще эти методы убрать. Но вроде бы фронтенд ждет username в ответ

2024-10-18 22:23 UTC, JOJOSoderqvist commented on internal/usecase/user/usecase.go
> +	return u.repo.GetUserByEmail(email)
Ну или есть еще 2 варианта
1) Если в middleware проверять только наличие сессии, то можно вообще эти методы убрать. Но вроде бы фронтенд ждет username в ответ о горе
2) Можно сделать отдельный интерфейс (специально для сессии) для репозитория где будет только getByEmail условно и напрямую его тыкать в Delivery, но я не знаю насколько это ок/не ок

2024-10-19 15:16 UTC, HallowAz commented on internal/delivery/auth/auth_manager.go
> +		Delivery: *user.NewUserDelivery(userU.NewUserUsecase(userR.NewUserMapRepository())),
Нет, не поправил. Всё ещё не так, как надо

2024-10-20 14:31 UTC, HallowAz commented on internal/delivery/auth/auth_manager.go
> +	Delivery user.UserDelivery
внешняя зависимость

2024-10-20 14:32 UTC, HallowAz commented on internal/delivery/auth/auth_manager.go
> +		Delivery: user.NewUserDelivery(userU.NewUserUseCase(userR.NewUserMapRepository())),
нет, не через интерфейсы делаешь, я это уже писал тебе

2024-10-20 14:35 UTC, HallowAz commented on internal/delivery/user/handler.go
> +type UsecaseInterface interface {
нет, не странно. Странно - это когда непонятно что делает интерфейс. А если у тебя будет не один интерфейс, то как тогда будешь действовать?

2024-10-20 14:36 UTC, HallowAz commented on internal/model/user_dto.go
> +	RepeatPassword string `json:"repeat_password"`
ок

2024-10-20 14:36 UTC, HallowAz commented on internal/usecase/user/usecase.go
> +type RepoInterface interface {
это не имеет значение, где реализация находится. Попробуй. всё получится

2024-10-20 14:36 UTC, HallowAz commented on internal/usecase/user/usecase.go
> +	return u.repo.GetUserByEmail(userLoginRequest.Email)
сразу вызвать следующий слой?

2024-10-20 14:37 UTC, HallowAz commented on internal/usecase/user/usecase.go
> +	return u.repo.GetUserByEmail(email)
второй вариант правильный

2024-10-20 14:37 UTC, HallowAz commented on internal/utils/json.go
> +	}
да, 500 надо, это внутренняя ошибка

2024-10-23 18:26 UTC, HallowAz commented on internal/app/http_server.go
> +		host, port, user, "123", dbname)
почему такие данные в открытом доступе

2024-10-23 18:28 UTC, HallowAz commented on internal/delivery/user/init.go
> +}
да, это победа, наконец-то

2024-10-23 18:28 UTC, HallowAz commented on internal/delivery/user/create_user.go
> +
а статус почему не проставил?

2024-10-23 18:29 UTC, HallowAz commented on internal/delivery/user/create_user.go
> +
или у вас там статус сам проставляется в утилите?

2024-10-23 18:31 UTC, HallowAz commented on internal/repository/user/get_user_by_email.go
> +	}
почему нет проверки на ErrNoRows? В таком случае должна быть кастомная ошибка

2024-10-23 18:32 UTC, HallowAz commented on internal/repository/user/get_user_by_email.go
> +	)
может сразу model.User создать тогда и в него сканить?

2024-10-23 18:32 UTC, HallowAz commented on internal/usecase/user/create_user.go
> +	return us.userManager.CreateUser(ctx, user)
менеджер и сервис это один и тот же слой, нельзя в проекте иметь и то,  и другое

2024-10-23 18:34 UTC, HallowAz commented on internal/usecase/user/init.go
> +}
нет, это один и тот же слой бизнес логики, надо переделать

2024-10-23 20:55 UTC, JOJOSoderqvist commented on internal/delivery/user/create_user.go
> +
Да, статус сам проставляется.

2024-10-23 20:55 UTC, JOJOSoderqvist commented on internal/delivery/user/create_user.go
> +	fmt.Println("Username: ", username)
Убрал

2024-10-23 20:58 UTC, JOJOSoderqvist commented on internal/app/http_server.go
> +		host, port, user, "123", dbname)
Убрал

2024-10-23 22:53 UTC, JOJOSoderqvist commented on internal/repository/user/get_user_by_email.go
> +	)
Сделал

2024-10-23 23:24 UTC, JOJOSoderqvist commented on internal/repository/user/get_user_by_email.go
> +	}
Поправил

2024-10-24 23:05 UTC, merged