[OZON-87] Добавлены сессии и redis
go-park-mail-ru/2024_2_kotyari pull request #19
Opened 2024-10-24 18:41 UTC by JOJOSoderqvist

2024-10-24 21:42 UTC, goriiin requested changes

2024-10-24 21:42 UTC, goriiin commented on internal/repository/sessions/create_session.go
> +	/// TODO: Remove magic constant
?

2024-10-24 21:42 UTC, goriiin commented on internal/utils/validate.go
> +		}
убрать, облегчили валидацию

2024-10-24 21:42 UTC, goriiin commented on internal/utils/validate.go
> +		}
вынести в методы структры, сделать интерфейс

2024-10-24 21:42 UTC, goriiin commented on internal/usecase/user/get_user_by_email.go
> +func (us *UsersService) GetUserByEmail(ctx context.Context, user model.User) (string, string, error) {
почему getUserByEmail создает сессию

2024-10-24 21:42 UTC, goriiin commented on internal/repository/user/get_user_by_email.go
> +		return model.User{}, err
лучше бы наверно обернуть ошибку, посмотри, мб еще где-то просто err возвращается

2024-10-24 21:42 UTC, goriiin commented on internal/usecase/user/create_user.go
> +		return "", "", err
оберни ошибку,
fmt.Errorf("[repo.CreateUser] ....)

 указывай какой-то контекст, так легче будет отследить

2024-10-24 21:42 UTC, goriiin commented on internal/repository/user/create_user.go
> +func (ur *UsersStore) CreateUser(ctx context.Context, userModel model.User) (uint32, string, error) {
может быть обернуть во что-то, 3 возвращаемых значения не круто

2024-10-24 21:42 UTC, goriiin commented on internal/usecase/user/create_user.go
> +	user.Password = hashedUserPassword
почему сразу не присвоил?...

2024-10-25 13:22 UTC, goriiin requested changes

2024-10-25 13:22 UTC, goriiin commented on internal/delivery/sessions/delete_session.go
> +			})
думаю не надо возвращать ошибку
если куки нет, значит уже удалены

2024-10-25 13:22 UTC, goriiin commented on internal/delivery/sessions/delete_session.go
> +		Name:     "session-id",
magic var

2024-10-25 13:22 UTC, goriiin commented on internal/delivery/sessions/delete_session.go
> +	http.SetCookie(w, &http.Cookie{
думаю стоит вынести в какой-нить initRmCookie или тп

2024-10-25 13:22 UTC, goriiin commented on internal/delivery/user/get_user_by_session_id.go
> +			utils.WriteJSON(w, http.StatusBadRequest, errs.HTTPErrorResponse{
здесь наверно стоит unauthorized возвращать

2024-10-25 13:22 UTC, goriiin commented on internal/delivery/user/get_user_by_session_id.go
> +	cookie, err := r.Cookie("session-id")
magic var

2024-10-25 13:22 UTC, goriiin commented on internal/errs/errors.go
> +var ErrCodesMapping = map[error]int{
сделать интерфейс с методом Get и RWMutex для map

2024-10-25 13:22 UTC, goriiin commented on internal/usecase/user/get_user_by_session_id.go
> +	return user.Username, user.City, nil
может вынести в структуру

2024-10-27 14:35 UTC, HallowAz commented on internal/app/http_server.go
> +	auth     *userDeliveryLib.UsersDelivery
почему не через интерфейсы?

2024-10-27 14:36 UTC, HallowAz commented on internal/app/http_server.go
> +	userService := userServiceLib.NewUserService(userRepo, *sessionsService)
зачем разыменовывать sessionsService?

2024-10-27 14:37 UTC, HallowAz commented on internal/app/http_server.go
> +	getUnimplemented.HandleFunc("/account", func(w http.ResponseWriter, r *http.Request) {
уже путаться начинаю во всем этом, мб у каждого сущности пусть будет свой регистратор урлов, а ты будешь их здесь вызывать?

2024-10-27 14:37 UTC, HallowAz commented on internal/app/http_server.go
> +	getUnimplemented.HandleFunc("/basket", func(w http.ResponseWriter, r *http.Request) {
почему basket, если это неправильное название?

2024-10-27 14:39 UTC, HallowAz commented on internal/app/http_server.go
> +	s.r.HandleFunc("/catalog", s.catalog.Products).Methods(http.MethodGet)
что такое catalog?

2024-10-27 14:39 UTC, HallowAz commented on internal/configs/redis/init.go
> +	"log"
поправь

2024-10-27 14:40 UTC, HallowAz commented on internal/configs/redis/init.go
> +		log.Fatal(err)
log fatal можно только в мейне использовать, здесь надо возвращать ошибку

2024-10-27 14:42 UTC, HallowAz commented on internal/delivery/user/create_user.go
> +		MaxAge:   3600,
я всё еще вижу магическую константу, не апрувну, пока она не исчезнет

2024-10-27 14:43 UTC, HallowAz commented on internal/delivery/user/init.go
> +type UsersDelivery struct {
почему где-то user, где-то users

2024-10-27 14:45 UTC, HallowAz commented on internal/repository/sessions/create_session.go
> +	/// TODO: Remove magic constant
3600

2024-10-27 14:46 UTC, HallowAz commented on internal/repository/user/create_user.go
> +		returning id, username, city;
заем тебе возвращать юзернейм, если он у тебя итак есть. И откуда у тебя city появится, если запись только создается?

2024-10-27 14:48 UTC, HallowAz commented on internal/usecase/user/get_user_by_session_id.go
> +	return user.Username, user.City, nil
может просто юзера и возвращать?

2024-10-27 15:32 UTC, JOJOSoderqvist commented on internal/usecase/user/get_user_by_session_id.go
> +	return user.Username, user.City, nil
Исправил

2024-10-27 15:32 UTC, JOJOSoderqvist commented on internal/app/http_server.go
> +	getUnimplemented.HandleFunc("/basket", func(w http.ResponseWriter, r *http.Request) {
Поменял

2024-10-27 15:32 UTC, JOJOSoderqvist commented on internal/app/http_server.go
> +	s.r.HandleFunc("/catalog", s.catalog.Products).Methods(http.MethodGet)
Главная страница приложения

2024-10-27 15:33 UTC, JOJOSoderqvist commented on internal/configs/redis/init.go
> +	"log"
Исправил

2024-10-27 15:40 UTC, JOJOSoderqvist commented on internal/repository/user/create_user.go
> +		returning id, username, city;
Исправил. City ставится по дефолту при добавлении в бд

2024-10-29 11:32 UTC, merged