[Ozon 83] заказы
go-park-mail-ru/2024_2_kotyari pull request #20
Opened 2024-10-27 21:23 UTC by KurenkovDmitry

2024-10-27 22:10 UTC, goriiin requested changes

2024-10-27 22:10 UTC, goriiin commented on assets/init.sql
> +    "id" UUID DEFAULT uuid_generate_v4(),
генерация должна быть в гошке, не нагружай базу

2024-10-28 00:20 UTC, goriiin requested changes

2024-10-28 00:20 UTC, goriiin commented on internal/delivery/orders/get_order_by_id.go
> +func (m *OrdersManager) GetOrderByID(ctx context.Context, id uint64) (*order.Order, error) {
возвращать нужно копию

2024-10-28 00:20 UTC, goriiin commented on internal/delivery/orders/get_order_by_id.go
> +func (m *OrdersManager) GetOrderByID(ctx context.Context, id uint64) (*order.Order, error) {
уровень delivery != manager

2024-10-28 00:20 UTC, goriiin commented on internal/delivery/orders/get_order_by_id.go
> +func (m *OrdersManager) GetOrderByID(ctx context.Context, id uint64) (*order.Order, error) {
почему ты с уровня деливери сразу вызываешь бд?
где ты будешь получать user id?

2024-10-28 00:20 UTC, goriiin commented on internal/handlers/orders/get_orders.go
> +	}
сделай какую-нить функцию

2024-10-28 00:20 UTC, goriiin commented on internal/handlers/orders/get_order_by_id.go
> +	}
в горилле можно более красиво сделать вроде

2024-10-28 00:20 UTC, goriiin commented on internal/handlers/orders/dto.go
> +}
сделай приватными

2024-10-28 00:34 UTC, goriiin requested changes

2024-10-28 00:34 UTC, goriiin commented on internal/repository/orders/init.go
> +}
добавь логгер

используем slog.log в папке configs

2024-10-28 00:34 UTC, goriiin commented on internal/repository/orders/get_orders.go
> +			productName  string
почему бы не юзать модель?

2024-10-28 00:34 UTC, goriiin commented on internal/repository/orders/get_orders.go
> +			productName  string
ну или дто

2024-10-28 00:34 UTC, goriiin commented on internal/repository/orders/get_order_by_id.go
> +func (r *OrdersRepo) GetOrderByID(ctx context.Context, id uuid.UUID) (*order.Order, error) {
в запросах не хватает отлова ошибки ErrNoRows

2024-10-28 00:34 UTC, goriiin commented on internal/model/orders/orders.go
> +}
зачем папка
почему в одном файле, это же разные модели, либо обозначь, что это конкретно ProductOrder

2024-10-28 00:34 UTC, goriiin commented on internal/handlers/orders/init.go
> +}
логгер

2024-10-28 00:34 UTC, goriiin commented on internal/handlers/orders/get_order_by_id.go
> +	}
используй utils.WriteJSON, пример в delivery.user

2024-10-29 14:38 UTC, JOJOSoderqvist requested changes

2024-10-29 14:38 UTC, JOJOSoderqvist commented on internal/repository/orders/get_orders.go
> +			productName  string
Лучше просто создать модель order и в нее все парсить

2024-10-31 20:43 UTC, HallowAz commented on internal/app/http_server.go
> +	s.r.HandleFunc("/orders/create_from_cart", s.orders.CreateOrderFromCart).Methods(http.MethodPost)
post /orders

2024-10-31 20:49 UTC, HallowAz commented on internal/repository/orders/create_order_from_cart.go
> +		GROUP BY c.user_id;
лучше вынести в бизнес логику проверки

2024-10-31 20:51 UTC, HallowAz commented on internal/repository/orders/get_order_by_id.go
> +func (r *OrdersRepo) GetOrderByID(ctx context.Context, id uuid.UUID, userID uint32) (*model.Order, error) {
большая функция

2024-10-31 20:52 UTC, HallowAz commented on internal/usecase/orders/create_order_from_cart.go
> +	return m.repo.CreateOrderFromCart(ctx, userID, address)
нет смысла в методе, т.к. он сразу вызывается

2024-11-02 22:51 UTC, goriiin requested changes

2024-11-02 22:51 UTC, goriiin commented on internal/repository/orders/create_order_from_cart.go
> +func (r *OrdersRepo) CreateOrderFromCart(ctx context.Context, orderID uuid.UUID, userID uint32, address string, totalPrice uint16, products []order.ProductOrder, deliveryDate time.Time) (*order.Order
модель в переменные

2024-11-02 23:00 UTC, goriiin requested changes

2024-11-02 23:00 UTC, goriiin commented on internal/delivery/orders/create_order_from_cart.go
> +		utils.WriteJSON(w, http.StatusInternalServerError, map[string]string{"error": "Failed to create order"})
?????? используй WriteErrorJSON

2024-11-02 23:00 UTC, goriiin commented on internal/delivery/orders/create_order_from_cart.go
> +	orderDTO := ToOrderDTO(*order)
копия

2024-11-03 14:28 UTC, HallowAz commented on internal/app/http_server.go
> +	getUnimplemented.HandleFunc("/order/{id}/{delivery_date}", s.orders.GetOrderByID).Methods(http.MethodGet)
что за delivery_date? Зачем его в пути передавать

2024-11-03 14:29 UTC, HallowAz commented on internal/delivery/orders/dto.go
> +}
выбери один стиль именования. Лучше для каждого запрсоа своё тело, как на 10-й строчке

2024-11-03 14:29 UTC, HallowAz commented on internal/delivery/orders/dto.go
> +	dtoOrders := make([]orderDTO, len(orders))
make([]orderDTO, 0, len(orders))

2024-11-03 14:29 UTC, HallowAz commented on internal/delivery/orders/dto.go
> +		dtoOrders[i] = ToOrderDTO(ord)
а здесь аппендить лучше

2024-11-03 14:33 UTC, HallowAz commented on internal/repository/orders/create_order_from_cart.go
> +func (r *OrdersRepo) CreateOrderFromCart(ctx context.Context, orderID uuid.UUID, userID uint32, address string, totalPrice uint16, products []order.ProductOrder, deliveryDate time.Time) (*order.Order
много парметров, лучше в структуру засунуть

2024-11-03 14:35 UTC, HallowAz commented on internal/repository/orders/create_order_from_cart.go
> +	}(tx, ctx)
у тебя в любом случае откатиться бд, получается в таком случае

2024-11-03 14:35 UTC, HallowAz commented on internal/repository/orders/create_order_from_cart.go
> +
в дефер, вместе с проверкой на ошибку и роллбеком

2024-11-03 14:37 UTC, HallowAz commented on internal/usecase/orders/get_orders.go
> +	for rows.Next() {
закрывать rows не надо потом?

2024-11-03 14:38 UTC, HallowAz commented on internal/usecase/orders/get_orders.go
> +	ordersMap := make(map[uuid.UUID]map[string]order.Order)
чето лютая структура, может можно проще?

2024-11-03 14:40 UTC, HallowAz commented on internal/usecase/orders/get_orders.go
> +}
ваще сложно чето, мне кажется надо подумать как упростить. Используй преимущества pgx

2024-11-03 14:41 UTC, HallowAz commented on internal/usecase/orders/get_orders.go
> +	for rows.Next() {
Почему у тебя слой менеджера работает с какими-то внешними структурами? Слой бизнес логики не должен зависеть ни от каких внешних сервисов

2024-11-04 21:15 UTC, merged